config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 post 'api/v1/login' => 'hcts_api#login', as: :hcts_api_login
 get 'api/v1/data' => 'hcts_api#get_data', as: :hcts_api_data
 post 'api/v1/create/sessiondata' => 'hcts_api#create_session_data', as: :hcts_api_create_session_data
 post 'api/v1/sessiondata/:id' => 'hcts_api#update_session_data', as: :hcts_api_update_session_data_post
 patch 'api/v1/sessiondata/:id' => 'hcts_api#update_session_data', as: :hcts_api_update_session_data_patch
 post 'api/v1/create/timesheet' => 'hcts_api#create_timesheet', as: :hcts_api_create_timesheet
 post 'api/v1/timesheet/:id' => 'hcts_api#update_timesheet', as: :hcts_api_update_timesheet_post
 patch 'api/v1/timesheet/:id' => 'hcts_api#update_timesheet', as: :hcts_api_update_timesheet_patch
 post 'api/v1/create/time/in' => 'hcts_api#create_time_in', as: :hcts_api_create_time_in
 post 'api/v1/timein/:id' => 'hcts_api#update_time_in', as: :hcts_api_update_time_in_post
 patch 'api/v1/timein/:id' => 'hcts_api#update_time_in', as: :hcts_api_update_time_in_patch
 post 'api/v1/create/time/out' => 'hcts_api#create_time_out', as: :hcts_api_create_time_out
 post 'api/v1/timeout/:id' => 'hcts_api#update_time_out', as: :hcts_api_update_time_out_post
 patch 'api/v1/timeout/:id' => 'hcts_api#update_time_out', as: :hcts_api_update_time_out_patch
 delete 'api/v1/careoptions/:id/delete' => 'hcts_api#empty_careoptions', as: :hcts_api_clear_careoptions
 post 'api/v1/careoptions' => 'hcts_api#set_careoptions', as: :hcts_api_set_careoptions
 post 'api/v1/create/files' => 'hcts_api#create_timesheet_files', as: :hcts_api_create_timesheet_files
 post 'api/v1/files/:id' => 'hcts_api#update_timesheet_files', as: :hcts_api_update_timesheet_files_post
 patch 'api/v1/files/:id' => 'hcts_api#update_timesheet_files', as: :hcts_api_update_timesheet_files_patch
 post 'api/v1/create/pca/signature' => 'hcts_api#create_pca_sign', as: :hcts_api_create_pca_sign
 post 'api/v1/recipientpassword' => 'hcts_api#verify_recipient_pass', as: :hcts_api_verify_recipient_pass
 post 'api/v1/create/recipient/signature' => 'hcts_api#create_recip_sign', as: :hcts_api_create_recip_sign
 post 'api/v1/finish/timesheets' => 'hcts_api#finish_timesheets', as: :hcts_api_finish_timesheets
 post 'api/v1/delete/timesheets' => 'hcts_api#delete_timesheets', as: :hcts_api_delete_timesheets
 get 'api/v1/pcas/:id' => 'hcts_api#get_pca', as: :hcts_api_get_pca
 get 'api/v1/counties' => 'hcts_api#get_counties', as: :hcts_api_get_counties
 get 'api/v1/qualifications' => 'hcts_api#get_qualifications', as: :hcts_api_get_qualifications
 post 'api/v1/devices' => 'hcts_api#set_device', as: :hcts_api_set_device
 post 'api/v1/requests' => 'hcts_api#set_request', as: :hcts_api_set_request
 get 'api/v1/requests/:id' => 'hcts_api#get_request', as: :hcts_api_get_request
 delete 'api/v1/requests/:id' => 'hcts_api#delete_request', as: :hcts_api_delete_request
 get 'api/v1/recipient/:id/requests' => 'hcts_api#get_requests_by_recipient', as: :hcts_api_get_requests_by_recipient
 get 'api/v1/pcas/:pca_id/available_requests' => 'hcts_api#get_available_requests', as: :hcts_api_get_available_requests
 get 'api/v1/pcas/:pca_id/accepted_requests' => 'hcts_api#get_accepted_requests', as: :hcts_api_get_accepted_requests
 post 'api/v1/pcas/:pca_id' => 'hcts_api#update_pca', as: :hcts_api_update_pca_post
 patch 'api/v1/pcas/:pca_id' => 'hcts_api#update_pca', as: :hcts_api_update_pca_patch
 post 'api/v1/pcas/:pca_id/image' => 'hcts_api#set_profile_image', as: :hcts_api_set_profile_image
 post 'api/v1/rsvps' => 'hcts_api#accept_request', as: :hcts_api_accept_request
 delete 'api/v1/rsvp/:rsvp_id' => 'hcts_api#decline_request', as: :hcts_api_decline_request
 get 'api/v1/pca/:pca_id/verify/:recipient_id' => 'hcts_api#need_verif', as: :hcts_api_check_verification
 post 'api/v1/verify/:verif_id' => 'hcts_api#verify', as: :hcts_api_verification_post
 patch 'api/v1/verify/:verif_id' => 'hcts_api#verify', as: :hcts_api_verification_patch
 post 'api/v1/verifcation/:verif_id/photo' => 'hcts_api#verification_photo', as: :hcts_api_verification_photo
 get 'api/v1/pca_contacts' => 'hcts_api#get_pca_contacts', as: :hcts_api_pca_contacts

 
 

 get 'recipient_dashboard' => 'home#recipient_dashboard', as: :recipient_dashboard
 get 'dashboard' => 'home#dashboard', as: :dashboard
 get 'privacy_policy' => 'home#privacy_policy', as: :privacy_policy
 get 'login' => 'home#login', as: :login
 post 'login' => 'home#login_post', as: :login_post
 get 'logout' => 'home#logout', as: :logout
 get 'sidebar-me' => 'home#testpage', as: :test_page
 get 'settings' => 'home#settings_redirect', as: :settings_redirect
 get 'users/archive/:id' => 'users#archive', as: :archive_user
 get 'users/dearchive/:id' => 'users#dearchive', as: :dearchive_user
 get 'agencies/:id/email' => 'agencies#email_settings', as: :agency_email_settings
 post 'agencies/:id/email' => 'agencies#email_submit', as: :agency_email_submit
 delete 'agencies/:agency_id/email/:id' => 'agencies#email_delete', as: :agency_email_delete
 get 'agencies/:id/subscription' => 'agencies#subscription', as: :agency_subscription_settings
 post 'agencies/:id/cancel_subscription' => 'agencies#cancel_subscription', as: :agency_cancel_subscription
 post 'agencies/:id/subscription' => 'agencies#subscription_submit', as: :agency_subscription_submit
 get 'agencies/:id/image' => 'agencies#get_image', as: :get_agency_image
 get 'assignments/' => 'assignments#index', as: :assignments
 get 'assignments/' => 'assignments#index', as: :assignments_index
 get 'assignments/new' => 'assignments#new', as: :new_assignment
 get 'assignments/:id/edit' => 'assignments#edit', as: :edit_assignment
 post 'assignments/new' => 'assignments#create', as: :recipient_pcas
 post 'assignments/:id/edit' => 'assignments#update', as: :update_assignment
 delete 'assignments/:id' => 'assignments#destroy', as: :destroy_assignment 
 get 'timesheets/get-zip' => 'timesheets#download_zip', as: :get_zip
 get 'timesheets/archive-all' => 'timesheets#archive_all', as: :archive_timesheets
 get 'timesheets/:id/archive' => 'timesheets#archive', as: :archive_timesheet
 get 'timesheets/:id/worker-sig' => 'timesheets#get_pca_sig', as: :get_pca_sig
 get 'timesheets/:id/recipient-sig' => 'timesheets#get_rec_sig', as: :get_rec_sig
 get 'timesheets/:id/download-pdf' => 'timesheets#download_pdf', as: :get_pdf
 get 'timesheets/:id/download-csv' => 'timesheets#download_csv', as: :get_csv
 get 'timesheets/:id/download-worker-sig' => 'timesheets#download_pca_sig', as: :download_pca_sig
 get 'timesheets/:id/download-recipient-sig' => 'timesheets#download_rec_sig', as: :download_rec_sig
 get 'verifications/:id/get-image' => 'verifications#get_image', as: :get_verif_image
 get 'get_time_in_form' => 'timesheets#get_time_in_form', as: :get_time_in_form

 get 'goals/' => 'goals#index', as: :goals_index
 get 'goals/new' => 'goals#new', as: :new_goal
 get 'goals/:id/edit' => 'goals#edit', as: :edit_goal
 post 'goals/new' => 'goals#create', as: :care_goals
 patch 'goals/:id' => 'goals#update', as: :care_goal
 get 'cares/' => 'care#index', as: :cares_index

 get 'users/:id/reset_pass' => 'users#reset_password', as: :reset_password
 post 'users/:id/reset_pass' => 'users#set_password', as: :set_password

 get 'forgot' => 'home#forgot', as: :forgot
 post 'forgot' => 'home#forgot_post', as: :forgot_post
 get 'reset' => 'home#reset_pass', as: :reset_pass
 post 'reset' => 'home#reset_pass_post', as: :reset_pass_post


  resources :verifications
  resources :timesheets
  resources :recipients
  resources :pcas
  resources :agencies
  resources :users
 get 'sign-up' => 'home#signup', as: :sign_up
 root 'home#login'


end

app/models/recipient.rb
class Recipient < ApplicationRecord
  self.table_name = "recipient"
  belongs_to :user, dependent: :destroy
  belongs_to :agency
  belongs_to :county
  has_many :recipient_pcas, dependent: :destroy
  has_many :pcas, through: :recipient_pcas
  has_many :timesheets
  has_many :session_data, through: :timesheets
  has_many :recipient_signatures, through: :timesheets
  has_many :requests, dependent: :destroy
  has_many :careoption_timesheets, through: :timesheets
  has_many :careoptions, through: :timesheets
  has_many :care_goals, dependent: :destroy
  has_many :goal_care_options, class_name: "Careoption", source: :goal_care_options, through: :care_goals
  has_many :recipient_services, dependent: :destroy
  has_many :services, through: :recipient_services
  accepts_nested_attributes_for :user

  scope :needs_goals, -> { where("id NOT IN (Select distinct(recipient_id) from care_goals)") }
  scope :has_goals, -> { where("id IN (Select distinct(recipient_id) from care_goals)") }
  scope :nonarchived, -> { joins(:user).where('fos_user.archived = ?', false) }
  scope :archived, -> { joins(:user).where('fos_user.archived = ?', true) }
  scope :from_archived_ts, -> { joins(:timesheets).where('timesheet.archived = ?', true) }

  after_find :decrypt_attrs

  before_save :encrypt_attrs
  after_save :check_user_name

  def name
    self.recipientName.titleize
  end

  def recipientName
    "#{self.first_name} #{self.last_name}"
  end

  def firstName
    self.first_name
  end

  def lastName
    self.last_name
  end

  def mANumber
    return Recipient.uncrypt(self.ma_number)
  end

  def companyAssignedId
    return Recipient.uncrypt(self.company_assigned_id)
  end

  def self.get_users
    User.nonarchived.where(id:self.pluck(:user_id))
  end

  def self.get_archived_users
    User.archived.where(id:self.pluck(:user_id))
  end

  def set_user
    self.user.firstName = self.first_name
    self.user.lastName = self.last_name
    self.recipient_name = "#{self.first_name} #{self.last_name}"
    self.user.roles = User::RECIP_ROLE
  end

  def gender_prefer
    case self.gender_preference
      when 1
        return "Female"
      when 2
        return "Male"
      else
        return "None"
    end
  end

  def self.get_frequency(array)
    array.group_by{ |v| v }.map{ |k, v| [k, v.size] }
    # array.each_with_object(Hash.new(0)){|key,hash| hash[key] += 1}
  end

  def compare_care_goals(timesheets = [])
    goals = self.goal_care_options
    resp = []
    if goals.present?
      goals_count = goals.count
      if timesheets.is_a? Timesheet
        timesheets = [timesheets]
      elsif !timesheets.present? 
        timesheets = self.timesheets.finished.active
      end
      tsheets = []
      timesheets.each do |ts|
        if ts.finished
          tsheets << ts
        end
      end
      timesheets = tsheets
      if timesheets.count > 10 
        timesheets = timesheets.first(10)
      end
      timesheets.sort_by{|x| x.session_datum.time_in.timeIn}
      timesheets.each do |ts|
        if ts.finished?
          careOps = ts.careoptions
          remainingCareOps = []
          if careOps.present?
            remainingCareOps = goals - careOps
            g_diff = remainingCareOps.count
          else
            g_diff = goals_count
          end
          perc = ((1 - g_diff/goals_count.to_f) * 100).round(2)
          resp << [ts, remainingCareOps, perc]
        end
      end
    end
    return resp
  end

  def graph_care_goals(timesheet_ids = [])
    goals = self.goal_care_options
    resp = {}
    colors = Recipient.graphColors.shuffle
    if goals.present?
      dataset = []
      dates = []
      goals_count = goals.count
      if timesheet_ids.is_a? Integer
        timesheet_ids = [timesheet_ids]
      elsif !timesheet_ids.present? 
        timesheet_ids = self.timesheets.graphable.pluck(:id)
      end
      tsheets = Timesheet.where(id:timesheet_ids).finished
      timesheets = tsheets.sort_by{|x| x.session_datum.time_in.timeIn}
      timesheets.each do |ts|
        date = "";
        if ts.recipient == self && ts.session_datum.present? && ts.finished
          session_data = ts.session_datum
          if session_data.time_in.present? && session_data.time_in.timeIn.present?
            stamp = session_data.time_in.timeIn.in_time_zone("Central Time (US & Canada)").to_time.to_i * 1000
            careOps = ts.careoptions
            remainingCareOps = []
            if careOps.present?
              remainingCareOps = goals - careOps
              g_diff = remainingCareOps.count
            else
              g_diff = goals_count
            end
            perc = ((1 - g_diff/goals_count.to_f) * 100).round(2)
            dataset << {x:stamp,y:perc}
          end
        end
      end
      resp[:data] = dataset
      color = colors.shift
      resp[:borderColor] = color[1]
      resp[:fill] = false
      resp[:backgroundColor] = color[0]
      resp[:label] = self.name
      resp[:lineTension] = 0
    end
    return resp
  end


  def self.graph_care_goals(timesheet_ids = [])
    resp = []
    if timesheet_ids.is_a? Integer
      timesheet_ids = [timesheet_ids]
    elsif !timesheet_ids.present? 
      return resp
    end
    colors = Recipient.graphColors.shuffle
    tsheets = Timesheet.where(id:timesheet_ids).active.finished
    timesheets = tsheets.sort_by{|x| x.session_datum.time_in.timeIn}
    if timesheets.count > 10 
      timesheets = timesheets.first(10)
    end
    recipients = Recipient.joins(:timesheets).where("timesheet.id in (?)",timesheet_ids).distinct
    recipients.each do |rec|
      datas = {}
      dataset = []
      dates = []
      goals = rec.goal_care_options
      goals_count = goals.count
      if goals_count > 0
        timesheets.each do |ts|
          date = "";
          if ts.recipient == rec && ts.session_datum.present? && ts.finished
            session_data = ts.session_datum
            if session_data.time_in.present? && session_data.time_in.timeIn.present?
              stamp = session_data.time_in.timeIn.in_time_zone("Central Time (US & Canada)").to_time.to_i * 1000
              careOps = ts.careoptions
              remainingCareOps = []
              if careOps.present?
                remainingCareOps = goals - careOps
                g_diff = remainingCareOps.count
              else
                g_diff = goals_count
              end
              perc = ((1 - g_diff/goals_count.to_f) * 100).round(2)
              dataset << {x:stamp,y:perc}
            end
          end
        end
        datas[:data] = dataset
        color = colors.shift
        datas[:borderColor] = color[1]
        datas[:fill] = false
        datas[:backgroundColor] = color[0]
        datas[:label] = rec.name
        datas[:lineTension] = 0
        resp << datas
      end
    end
    return resp
  end
  

  def bar_cares(timesheet_ids = [])
    resp = {}
    if timesheet_ids.is_a? Integer
      timesheet_ids = [timesheet_ids]
    elsif !timesheet_ids.present?
      timesheet_ids = self.timesheets.finished.pluck(:id)
    end
    colors = Recipient.graphColors.shuffle
    if timesheet_ids.count > 10 
      timesheet_ids = timesheet_ids.first(10)
    end
    careoptions = Recipient.get_care_options(timesheet_ids)
    datasets = []
    timesheet_ids.each do |t_id|
      ts = Timesheet.find_by(id:t_id)
      if ts.present? && ts.finished?
        dataset = {}
        careOps = Recipient.get_care_options(t_id)
        data = []
        careoptions.each do |c|
          if careOps.include?(c)
            data << 1
          else
            data << 0
          end
        end
        dataset[:data] = data
        dataset[:label] = "#{ts.pca.name} - #{Timesheet.get_date_range(ts)}"
        color = colors.shift
        dataset[:backgroundColor] = Array.new(data.length, color[0])
        dataset[:borderColor] = Array.new(data.length, color[1])
        dataset[:borderWidth] = 1
        datasets << dataset    
      end
    end
    goals = self.get_goal_care_options
    resp[:labels] = careoptions.map{|x| goals.include?(x) ? "#{x} (CG)" : x }
    resp[:datasets] = datasets
    return resp
  end

  def self.bar_cares(timesheet_ids = [])
    resp = {}
    if timesheet_ids.is_a? Integer
      timesheet_ids = [timesheet_ids]
    elsif !timesheet_ids.present?
      return resp
    end
    if timesheet_ids.count > 10
      timesheet_ids = timesheet_ids.first(10)
    end
    colors = Recipient.graphColors.shuffle
    careoptions = Recipient.get_care_options(timesheet_ids)
    datasets = []
    timesheet_ids.each do |t_id|
      ts = Timesheet.find_by(id:t_id)
      if ts.present? && ts.finished
        dataset = {}
        careOps = Recipient.get_care_options(t_id)
        data = []
        careoptions.each do |c|
          if careOps.include?(c)
            data << 1
          else
            data << 0
          end
        end
        dataset[:data] = data
        dataset[:label] = "#{ts.recipient.name}-#{ts.pca.name} #{Timesheet.get_date_range(ts)}"
        color = colors.shift
        dataset[:backgroundColor] = Array.new(data.length, color[0])
        dataset[:borderColor] = Array.new(data.length, color[1])
        dataset[:borderWidth] = 1
        datasets << dataset    
      end
    end
    resp[:labels] = careoptions
    resp[:datasets] = datasets
    return resp
  end


  def get_goal_care_options
    self.goal_care_options.map{|x| x.name}
  end


  def self.get_care_options(timesheet_ids)
    Careoption.joins(:timesheets).where("timesheet.id in (?)",timesheet_ids).distinct.map{|x| x.name}
  end


  def self.get_range_name(datasets)
    resp = "month"
    dates = []
    datasets[:datasets].each do |d|
      data = d[:data]
      dates << data[0][:x]/100
      dates << data[data.size-1][:x]/100
    end
    dates.sort!
    range = dates.last - dates.first
    if range > 0 
      num_days = range/84600
      if num_days < 2
        resp = "hour"
      elsif num_days < 30
        resp = "day"
      end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/recipients/_form.html.haml
= form_for @recipient do |f|
  %div.container-full.grid-container.formBox.panel-back
    %table
      - if action_name != "create" && action_name != "new"
        %thead
          %tr
            %th{colspan:"3"}
              .left-filter
                %span= link_to "Set Care Goals", new_goal_path(recipient_id:@recipient.id)
                %span &middot;
                %span= link_to "Reset Password", reset_password_path(@recipient.user.id)
              %hr
      %tbody
        - if @recipient.errors.any?
          %tr
            %td{colspan:"3"}
              #errors
                %h2= "#{pluralize(@recipient.errors.count, "error")} prohibited this recipient from being saved:"
                %ul
                  - @recipient.errors.full_messages.each do |message|
                    %li= message
        %tr
          %td
            %table
              - if @agency.present?
                = f.hidden_field :agency_id, value:@agency.id
              - else
                %tr  
                  %td.fieldTitle Agency
                  %td.field= f.collection_select :agency_id, Agency.all, :id, :name
              %tr
                %td.fieldTitle First Name
                %td.field= f.text_field :first_name
              %tr
                %td.fieldTitle Last Name
                %td.field= f.text_field :last_name
              %tr
                %td.fieldTitle MA Number
                %td.field= f.text_field :ma_number
              %tr
                %td.fieldTitle Company Assigned Id
                %td.field= f.text_field :company_assigned_id
              %tr
                %td.fieldTitle Home Address
                %td.field= f.text_field :home_address
              %tr
                %td.fieldTitle County
                %td.field= f.collection_select :county_id, County.all, :id, :name 
              %tr
                %td{colspan:"2"}
                  %h2.tableTitle Login Credentials
              = f.fields_for :user do |u|
                %tr
                  %td.fieldTitle Username
                  %td.field= u.text_field :username
                %tr
                  %td.fieldTitle Email
                  %td.field= u.email_field :email
                - if action_name == "create" || action_name == "new"
                  %tr
                    %td.fieldTitle Password
                    %td.field= u.password_field :password
                  %tr
                    %td.fieldTitle Verify Password
                    %td.field= u.password_field :password_confirmation
                - if @recipient.user.present? && @recipient.user.archived
                  %tr
                    %td.fieldTitle Archived
                    %td.field.left-align= u.check_box :archived
              %tr
                %td{colspan:"2"}
                  %h2.tableTitle App Options
              %tr
                %td.fieldTitle Gender Preference
                %td.field= f.select :gender_preference, Recipient.gender_preferences
              %tr
                %td.fieldTitle Skip Verification
                %td.field.left-align= f.check_box :skip_verification
              %tr
                %td.fieldTitle Skip GPS
                %td.field.left-align= f.check_box :skip_gps
          %td{style: "width: 4rem"}
          %td{style:"vertical-align:top; padding-top:0"}
            %table
              %tr
                %td{colspan:"2", style:"padding-top:0"}
                  %h2.tableTitle Services
              = f.collection_check_boxes(:service_ids, @services, :id, :name) do |s|
                %tr
                  %td.field.right= s.check_box
                  %td.fieldTitle.left-align= s.label
        %tr
          %td.actions{colspan:"3"}
            = link_to 'Cancel', 'javascript:history.back()'
            = f.submit 'Save'

app/views/recipients/edit.html.haml
- @page_title = "Edit:  #{@recipient.name}"
- @partial = true 
= render 'form'

app/views/recipients/index.html.haml
%h1.pageTitle Listing recipients
%div.users.container-full.grid-container
  %table.fullTable.col-12.table-shadow
    %thead
      %tr
        %th User
        %th Agency
        %th Skip verification
        %th Skip gps
        %th First name
        %th Last name
        %th Ma number
        %th Company assigned
        %th Gender preference
        %th County
        %th Home address
        %th
        %th
        %th

    %tbody
      - @recipients.each do |recipient|
        %tr
          %td= recipient.user_id
          %td= recipient.agency_id
          %td= recipient.skip_verification
          %td= recipient.skip_gps
          %td= recipient.first_name
          %td= recipient.last_name
          %td= recipient.ma_number
          %td= recipient.company_assigned_id
          %td= recipient.gender_preference
          %td= recipient.county_id
          %td= recipient.home_address
          %td= link_to 'Show', recipient
          %td= link_to 'Edit', edit_recipient_path(recipient)
          %td= link_to 'Destroy', recipient, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Recipient', new_recipient_path

app/views/recipients/new.html.haml
- @page_title = "New Recipient"
- @partial = true
= render 'form'

app/views/recipients/show.html.haml
- @page_title = "About: #{@recipient.name}"
%p.left-filter.half
  = link_to 'Edit', edit_recipient_path(@recipient)
  %span &middot;
  = link_to 'Recipient Admin', users_path(recipient_id:@recipient.id)

%div.showFrame
  %table.shoTable
    %thead{colspan: "3"}
      %tr
        %th User:
        %td= @recipient.user.name
      %tr
        %th Agency:
        %td= @recipient.agency.name
      %tr
        %th First Name:
        %td= @recipient.first_name
      %tr
        %th Last Name:
        %td= @recipient.last_name
      %tr
        %th MA Number:
        %td= @recipient.ma_number
      %tr
        %th Company Assigned:
        %td= @recipient.company_assigned_id
    %thead{colspan: "3"}
      %tr
        %th Home Address:
        %td= @recipient.home_address
      %tr
        %th County:
        %td= @recipient.county.name
      %tr
        %th Gender Preference:
        %td= @recipient.gender_prefer
      %tr
        %th Skip Verification:
        %td= @recipient.skip_verification
      %tr
        %th Skip GPS:
        %td= @recipient.skip_gps