config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 post 'api/v1/login' => 'hcts_api#login', as: :hcts_api_login
 get 'api/v1/data' => 'hcts_api#get_data', as: :hcts_api_data
 post 'api/v1/create/sessiondata' => 'hcts_api#create_session_data', as: :hcts_api_create_session_data
 post 'api/v1/sessiondata/:id' => 'hcts_api#update_session_data', as: :hcts_api_update_session_data_post
 patch 'api/v1/sessiondata/:id' => 'hcts_api#update_session_data', as: :hcts_api_update_session_data_patch
 post 'api/v1/create/timesheet' => 'hcts_api#create_timesheet', as: :hcts_api_create_timesheet
 post 'api/v1/timesheet/:id' => 'hcts_api#update_timesheet', as: :hcts_api_update_timesheet_post
 patch 'api/v1/timesheet/:id' => 'hcts_api#update_timesheet', as: :hcts_api_update_timesheet_patch
 post 'api/v1/create/time/in' => 'hcts_api#create_time_in', as: :hcts_api_create_time_in
 post 'api/v1/timein/:id' => 'hcts_api#update_time_in', as: :hcts_api_update_time_in_post
 patch 'api/v1/timein/:id' => 'hcts_api#update_time_in', as: :hcts_api_update_time_in_patch
 post 'api/v1/create/time/out' => 'hcts_api#create_time_out', as: :hcts_api_create_time_out
 post 'api/v1/timeout/:id' => 'hcts_api#update_time_out', as: :hcts_api_update_time_out_post
 patch 'api/v1/timeout/:id' => 'hcts_api#update_time_out', as: :hcts_api_update_time_out_patch
 delete 'api/v1/careoptions/:id/delete' => 'hcts_api#empty_careoptions', as: :hcts_api_clear_careoptions
 post 'api/v1/careoptions' => 'hcts_api#set_careoptions', as: :hcts_api_set_careoptions
 post 'api/v1/create/files' => 'hcts_api#create_timesheet_files', as: :hcts_api_create_timesheet_files
 post 'api/v1/files/:id' => 'hcts_api#update_timesheet_files', as: :hcts_api_update_timesheet_files_post
 patch 'api/v1/files/:id' => 'hcts_api#update_timesheet_files', as: :hcts_api_update_timesheet_files_patch
 post 'api/v1/create/pca/signature' => 'hcts_api#create_pca_sign', as: :hcts_api_create_pca_sign
 post 'api/v1/recipientpassword' => 'hcts_api#verify_recipient_pass', as: :hcts_api_verify_recipient_pass
 post 'api/v1/create/recipient/signature' => 'hcts_api#create_recip_sign', as: :hcts_api_create_recip_sign
 post 'api/v1/finish/timesheets' => 'hcts_api#finish_timesheets', as: :hcts_api_finish_timesheets
 post 'api/v1/delete/timesheets' => 'hcts_api#delete_timesheets', as: :hcts_api_delete_timesheets
 get 'api/v1/pcas/:id' => 'hcts_api#get_pca', as: :hcts_api_get_pca
 get 'api/v1/counties' => 'hcts_api#get_counties', as: :hcts_api_get_counties
 get 'api/v1/qualifications' => 'hcts_api#get_qualifications', as: :hcts_api_get_qualifications
 post 'api/v1/devices' => 'hcts_api#set_device', as: :hcts_api_set_device
 post 'api/v1/requests' => 'hcts_api#set_request', as: :hcts_api_set_request
 get 'api/v1/requests/:id' => 'hcts_api#get_request', as: :hcts_api_get_request
 delete 'api/v1/requests/:id' => 'hcts_api#delete_request', as: :hcts_api_delete_request
 get 'api/v1/recipient/:id/requests' => 'hcts_api#get_requests_by_recipient', as: :hcts_api_get_requests_by_recipient
 get 'api/v1/pcas/:pca_id/available_requests' => 'hcts_api#get_available_requests', as: :hcts_api_get_available_requests
 get 'api/v1/pcas/:pca_id/accepted_requests' => 'hcts_api#get_accepted_requests', as: :hcts_api_get_accepted_requests
 post 'api/v1/pcas/:pca_id' => 'hcts_api#update_pca', as: :hcts_api_update_pca_post
 patch 'api/v1/pcas/:pca_id' => 'hcts_api#update_pca', as: :hcts_api_update_pca_patch
 post 'api/v1/pcas/:pca_id/image' => 'hcts_api#set_profile_image', as: :hcts_api_set_profile_image
 post 'api/v1/rsvps' => 'hcts_api#accept_request', as: :hcts_api_accept_request
 delete 'api/v1/rsvp/:rsvp_id' => 'hcts_api#decline_request', as: :hcts_api_decline_request
 get 'api/v1/pca/:pca_id/verify/:recipient_id' => 'hcts_api#need_verif', as: :hcts_api_check_verification
 post 'api/v1/verify/:verif_id' => 'hcts_api#verify', as: :hcts_api_verification_post
 patch 'api/v1/verify/:verif_id' => 'hcts_api#verify', as: :hcts_api_verification_patch
 post 'api/v1/verifcation/:verif_id/photo' => 'hcts_api#verification_photo', as: :hcts_api_verification_photo
 get 'api/v1/pca_contacts' => 'hcts_api#get_pca_contacts', as: :hcts_api_pca_contacts

 
 

 get 'recipient_dashboard' => 'home#recipient_dashboard', as: :recipient_dashboard
 get 'dashboard' => 'home#dashboard', as: :dashboard
 get 'privacy_policy' => 'home#privacy_policy', as: :privacy_policy
 get 'login' => 'home#login', as: :login
 post 'login' => 'home#login_post', as: :login_post
 get 'logout' => 'home#logout', as: :logout
 get 'sidebar-me' => 'home#testpage', as: :test_page
 get 'settings' => 'home#settings_redirect', as: :settings_redirect
 get 'users/archive/:id' => 'users#archive', as: :archive_user
 get 'users/dearchive/:id' => 'users#dearchive', as: :dearchive_user
 get 'agencies/:id/email' => 'agencies#email_settings', as: :agency_email_settings
 post 'agencies/:id/email' => 'agencies#email_submit', as: :agency_email_submit
 delete 'agencies/:agency_id/email/:id' => 'agencies#email_delete', as: :agency_email_delete
 get 'agencies/:id/subscription' => 'agencies#subscription', as: :agency_subscription_settings
 post 'agencies/:id/cancel_subscription' => 'agencies#cancel_subscription', as: :agency_cancel_subscription
 post 'agencies/:id/subscription' => 'agencies#subscription_submit', as: :agency_subscription_submit
 get 'agencies/:id/image' => 'agencies#get_image', as: :get_agency_image
 get 'assignments/' => 'assignments#index', as: :assignments
 get 'assignments/' => 'assignments#index', as: :assignments_index
 get 'assignments/new' => 'assignments#new', as: :new_assignment
 get 'assignments/:id/edit' => 'assignments#edit', as: :edit_assignment
 post 'assignments/new' => 'assignments#create', as: :recipient_pcas
 post 'assignments/:id/edit' => 'assignments#update', as: :update_assignment
 delete 'assignments/:id' => 'assignments#destroy', as: :destroy_assignment 
 get 'timesheets/get-zip' => 'timesheets#download_zip', as: :get_zip
 get 'timesheets/archive-all' => 'timesheets#archive_all', as: :archive_timesheets
 get 'timesheets/:id/archive' => 'timesheets#archive', as: :archive_timesheet
 get 'timesheets/:id/worker-sig' => 'timesheets#get_pca_sig', as: :get_pca_sig
 get 'timesheets/:id/recipient-sig' => 'timesheets#get_rec_sig', as: :get_rec_sig
 get 'timesheets/:id/download-pdf' => 'timesheets#download_pdf', as: :get_pdf
 get 'timesheets/:id/download-csv' => 'timesheets#download_csv', as: :get_csv
 get 'timesheets/:id/download-worker-sig' => 'timesheets#download_pca_sig', as: :download_pca_sig
 get 'timesheets/:id/download-recipient-sig' => 'timesheets#download_rec_sig', as: :download_rec_sig
 get 'verifications/:id/get-image' => 'verifications#get_image', as: :get_verif_image
 get 'get_time_in_form' => 'timesheets#get_time_in_form', as: :get_time_in_form

 get 'goals/' => 'goals#index', as: :goals_index
 get 'goals/new' => 'goals#new', as: :new_goal
 get 'goals/:id/edit' => 'goals#edit', as: :edit_goal
 post 'goals/new' => 'goals#create', as: :care_goals
 patch 'goals/:id' => 'goals#update', as: :care_goal
 get 'cares/' => 'care#index', as: :cares_index

 get 'users/:id/reset_pass' => 'users#reset_password', as: :reset_password
 post 'users/:id/reset_pass' => 'users#set_password', as: :set_password

 get 'forgot' => 'home#forgot', as: :forgot
 post 'forgot' => 'home#forgot_post', as: :forgot_post
 get 'reset' => 'home#reset_pass', as: :reset_pass
 post 'reset' => 'home#reset_pass_post', as: :reset_pass_post


  resources :verifications
  resources :timesheets
  resources :recipients
  resources :pcas
  resources :agencies
  resources :users
 get 'sign-up' => 'home#signup', as: :sign_up
 root 'home#login'


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 skip_before_action :set_current_user, only: [:login, :login_post, :privacy_policy, :forgot, :forgot_post, :reset_pass, :reset_pass_post, :signup]
 before_action :check_current_user, only: [:login] 

 def login
  
 end

 def signup
   redirect_to new_agency_url
 end

 def login_post
  @errors = []
  if params.has_key?("username") && params.has_key?("password")
    pass = params[:password]
    username = params[:username]
    @user = User.find_by(username:username)
    if @user.present? && @user.authenticate_password(pass)
      is_agent = @user.is_agent?
      is_admin = @user.is_admin?
      if is_agent || is_admin
          @current_user = @user
          @user.last_login = DateTime.now
          @user.save
          session[:current_user_id] = @user.id
        if is_agent
          redirect_to dashboard_path
        elsif is_admin
          redirect_to agencies_path
        else
          @errors << "Unauthorized"
          render 'login'
        end
      elsif @user.is_pca?
        @current_user = @user
        @user.last_login = DateTime.now
        @user.save
        session[:current_user_id] = @user.id
        redirect_to edit_pca_path(@user.pca)
      elsif @user.is_recipient? && @user.recipient.agency.present? && @user.recipient.agency.pca_finder_active
        @current_user = @user
        @user.last_login = DateTime.now
        @user.save
        session[:current_user_id] = @user.id
        redirect_to users_path
      else
        @errors << "Unauthorized"
        render 'login'
      end 
    else
      @errors << "Username or password incorrect"
      render 'login'
    end
  else
    @errors << "Username and password required"
    render 'login' 
  end
 end

 def logout
   session.destroy
   redirect_to login_path
 end


 def dashboard
   if @current_user.is_admin?
     @agency = Agency.find_by(id:session[:current_agency_id])
   end
   
   if !@agency.present?
     @agency = @current_user.agency
   end
 end

 def forgot
 end
  
 def forgot_post
   @errors = []
   if params.has_key?("email") && params[:email].present?
     get_username = params.has_key?("username") && params[:username].present?
     get_pass = params.has_key?("password") && params[:password].present?
     @user = User.find_by(email:params[:email])
     if get_username || get_pass
       if @user.present?
         if get_username
           AdminMailer.send_username(@user).deliver_now
         end
         if get_pass
           @user.gen_pass_token
           AdminMailer.send_password(@user).deliver_now
         end
       else
         @errors << "No User found"
       end
     else
       @errors << "Select Either Username or Password"
     end
   else
     @errors << "Email Required"
   end 
   if @errors.empty?
     redirect_to login_path, notice: "Email Sent"
   else
     render 'forgot'
   end
 end

 def reset_pass
   message = nil
   if params.has_key?("token") && params[:token].present?
     @token = params[:token]
     @user = User.find_by(confirmation_token:params[:token])
     if !@user.present? 
       message = "No User Found"
     elsif @user.password_requested_at < Time.now - 24.hours
       message = "Request Expired"
     end
   else
     redirect_to login_path
   end
   if message.present?
     redirect_to forgot_path, alert: message
   end
 end

 def reset_pass_post
   message = nil
   @errors = []
   if params.has_key?("token") && params[:token].present?
     @user = User.find_by(confirmation_token:params[:token])
     if !@user.present?
       message = "Request Not Found"
     elsif @user.password_requested_at < Time.now - 24.hours
       message = "Request Expired"
     else
       if params.has_key?("password") && params[:password].present?
         if params.has_key?("password_confirmation") && params[:password_confirmation] == params[:password]
           @user.password = params[:password]
           @user.password_confirmation = params[:password]
           @user.save
         else
           @errors << "Password Confirmation does not match"
         end
       end
     end
   else
     message = "Request Not Found"
   end
   if message.present?
     redirect_to forgot_path, alert: message
   elsif @errors.empty?
     redirect_to login_path, notice: "Password Successfully Reset"
   else
     render 'reset_pass'
   end
 end

 def testpage

 end

 def privacy_policy
 end
 
 def settings_redirect
   if @current_user.is_agent?
     redirect_to edit_agency_path(@current_user.agency)
   elsif @current_user.is_pca?
     redirect_to @current_user
   elsif @current_user.is_recipient?
     redirect_to @current_user
   elsif @current_user.is_admin?
     if session[:current_agency_id].present?
       redirect_to edit_agency_path(id:session[:current_agency_id])
     else
       redirect_to agencies_path
     end
   else
     redirect_to dashboard_path
   end
 end
 
 def recipient_dashboard
 end


private 

  def check_current_user
    if session[:current_user_id].present?
      user = User.find_by(id:session[:current_user_id])
      if user.present?
        @current_user = user
      end
    end
    if @current_user.present?
      if @current_user.is_admin?
        redirect_to agencies_path
      else
        redirect_to dashboard_path
      end
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/dashboard.html.haml
.container-full.dashboard
  - if @current_user.is_recipient?
    .row
      = link_to users_path do
        .dashCell
          %span#icon.fa.fa-users{"aria-hidden" => "true"}
          .dashTitle
            %h4 Browse PCAs
  - else
    .row
      = link_to users_path do
        .dashCell
          %span#icon.fa.fa-users{"aria-hidden" => "true"}
          .dashTitle
            %h4 Manage Users
      = link_to timesheets_path(finished:"Yes") do 
        .dashCell
          %span#icon.fa.fa-clock-o{"aria-hidden" => "true"}
          .dashTitle
            %h4 Time Entries
      = link_to assignments_path do 
        .dashCell
          %span#icon.fa.fa-handshake-o{"aria-hidden" => "true"}
          .dashTitle
            %h4 Make Assignments
      = link_to verifications_path do
        .dashCell
          %span#icon.fa.fa-check-square-o{"aria-hidden" => "true"}
          .dashTitle
            %h4 Verify History 
      = link_to goals_index_path do
        .dashCell
          .valuePack
            - if @agency.present?
              .dashValues= "#{(@agency.goal_average).round}%"
            - else
              .dashValues 100%
          .dashTitle
            %h4 Compared to goals
      = link_to settings_redirect_path do 
        .dashCell
          %span#icon.fa.fa-cog{"aria-hidden" => "true"}
          .dashTitle
            %h4 Settings

app/views/home/forgot.html.haml
.container-full.vrtCntr
  %div.login-container
    %div.login-heading
      - if request.host == 'pcafinder.besthomecaremn.com' || request.host == 'pcafindertest.besthomecaremn.com'
        = image_tag("besthomecare-logo-03.png", class: "logoImg")
      - else
        = image_tag("hct-logo4.png", class: "logoImg")
      -#%h3.form-signin-heading Homecare Timesheets
    =form_tag( forgot_post_path, method:"post", :class => "form-signin") do 
      %p#alert= alert
      %div
        %p.log-title Email Address
        %input#username.logform-control{:autofocus => "", :name => "email", :placeholder => "", :type => "text", :required => true}/
        #login-content.centered
          - if @errors.present? && @errors.any?
            #errors
              %ul
                - @errors.each do |message|
                  %li= message
        %div.login-checkbox
          %input{ :type => "checkbox", :id => "checkbox", :name => "username", :value => "option1", :aria-label => "..."}/
          %label.logme Send Username
        %div.login-checkbox
          %input{ :type => "checkbox", :id => "checkbox", :name => "password", :value => "option1", :aria-label => "..."}/
          %label.logme Send Password Reset
        %button.btn-block{:type => "submit"} Submit
        %div.form-bottom
    .container.footer
  %p= "&copy #{Time.now.year} PCA Partners Inc.".html_safe

app/views/home/login.html.haml
.container-full.vrtCntr
  %div.login-container
    %div.login-heading
      - if request.host == 'pcafinder.besthomecaremn.com' || request.host == 'pcafindertest.besthomecaremn.com'
        = image_tag("besthomecare-logo-03.png", class: "logoImg")
      - else
        = image_tag("hct-logo4.png", class: "logoImg")
      -#%h3.form-signin-heading Homecare Timesheets
    =form_tag( login_post_path, method:"post", :class => "form-signin") do 
      %p#notice= notice
      - if request.host == 'pcafinder.besthomecaremn.com' || request.host == 'pcafindertest.besthomecaremn.com'
        %p
          %strong Looking for an employee? <br/>
          Login in to your account to search our employee database. 
        %p
          %strong Don't have an account? <br/>
          Contact client services to set up an account.
      %div
        %p.log-title Username
        %input#username.logform-control{:autofocus => "", :name => "username", :placeholder => "", :type => "text", :required => true}/
        %p.log-title Password
        %input.logform-control{:name => "password", :placeholder => "", :type => "password", :required => true}/
        #login-content.centered
          - if @errors.present? && @errors.any?
            #errors
              %ul
                - @errors.each do |message|
                  %li= message
        %button.btn-block{:type => "submit"} Login
        %div.form-bottom
          = link_to "Forgot username or password", forgot_path, class:"login-forgot"
    .container.footer
  %p= "&copy #{Time.now.year} PCA Partners Inc.".html_safe

app/views/home/privacy_policy.html.haml
.panel-back.grid-container.container-full.thin
  %h1.pageTitle PCA PARTNERS TERMS OF SERVICE
  %h2.tableTitle Welcome to PCA Partners (PCAP) Homecare Timesheets and PCA On Demand
  %p
    Thanks for using our products and ("Services"). The Services are provided by PCA Partners, located at 2562 7th Avenue Suite 201, North Saint Paul, MN 55109, United States.
  %p
    By using our Products and Services, you are agreeing to these terms. Please read them carefully.

  %h2.tableTitle Using our Services

  %p You must follow any policies made available to you within the Services.

  %p Don’t misuse our Services. For example, don’t interfere with our Services or try to access them using a method other than the interface and the instructions that we provide. You may use our Services only as permitted by law, including applicable export and re-export control laws and regulations. We may suspend or stop providing our Services to you if you do not comply with our terms or policies or if we are investigating suspected misconduct.

  %p Using our Services does not give you ownership of any intellectual property rights in our Services or the content you access. These terms do not grant you the right to use any branding or logos used in our Services. Don’t remove, obscure, or alter any legal notices displayed in or along with our Services.

  %p You shall not (a) attempt to copy, modify, duplicate, create derivative works, from, frame, mirror, republish, download, display, transmit, or distribute all or any portion of our products in any form or media or by any means; (b) attempt to reverse engineer, or otherwise reduce to human-perceivable form all or any part of our products in order to build a product or service which competes with PCAP; (c) license, sell, rent, lease, transfer, assign, distribute, display, disclose or otherwise commercially exploit, or otherwise make our products available to any third party; or (d) attempt to obtain, or assist third parties in obtaining access to our products.
  %p Some of our Services are available on mobile devices. Do not use such Services in a way that distracts you and prevents you from obeying traffic or safety laws.
  %h1.pageTitle Privacy and Copyright Protection
  %p PCAP privacy policies explain how we treat your personal data and protect your privacy when you use our Services. By using our Services, you agree that PCAP can use such data in accordance with our privacy policies.
  %h2.tableTitle Modifying and Terminating our Services
  %p We are constantly changing and improving our Services. We may add or remove functionalities or features, and we may suspend or stop a Service altogether.

  %p You can stop using our Services at any time, although we’ll be sorry to see you go. PCAP may also stop providing Services to you, or add or create new limits to our Services at any time.

  %p We believe that you own your data and preserving your access to such data is important. If we discontinue a Service, where reasonably possible, we will give you reasonable advance notice and a chance to get information out of that Service.
  %h2.tableTitle Our Warranties and Disclaimers

  %p We provide our Services using a commercially reasonable level of skill and care and we hope that you will enjoy using them. But there are certain things that we don’t promise about our Services.

  %p OTHER THAN AS EXPRESSLY SET OUT IN THESE TERMS OR ADDITIONAL TERMS, NEITHER PCAP NOR ITS SUPPLIERS OR DISTRIBUTORS MAKE ANY SPECIFIC PROMISES ABOUT THE SERVICES. FOR EXAMPLE, WE DON’T MAKE ANY COMMITMENTS ABOUT THE CONTENT WITHIN THE SERVICES, THE SPECIFIC FUNCTIONS OF THE SERVICES, OR THEIR RELIABILITY, AVAILABILITY, OR ABILITY TO MEET YOUR NEEDS. WE PROVIDE THE SERVICES “AS IS”.

  %p SOME JURISDICTIONS PROVIDE FOR CERTAIN WARRANTIES, LIKE THE IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, WE EXCLUDE ALL WARRANTIES.

  %p PCAP EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, REGARDING THE ACCURACY, COMPLETENESS OR PERFORMANCE OF PRODUCTS OR SERVICES.
  %h2.tableTitle Limitation of Liability

  %p IN NO EVENT WILL PCAP BE LIABLE TO CUSTOMER FOR ANY SPECIAL, INCIDENTAL, PUNITIVE, INDIRECT, EXEMPLARY, OR CONSEQUENTIAL DAMAGES, INCLUDING, WITHOUT LIMITATION, LOST PROFITS, LOST REVENUES, LOSS OF USE, LOSS OF DATA, OR LOSS OF GOODWILL OR REPUTATION, ARISING OUT OF OR IN CONNECTION WITH THE USE OF PCAP PRODUCTS OR SERVICES, WHETHER SUCH LIABILITY ARISES FROM ANY CLAIM BASED UPON BREACH OF CONTRACT, BREACH OF WARRANTY, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY, OR OTHERWISE, AND WHETHER OR NOT A CUSTOMER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE AND EVEN IF SUCH DAMAGES WERE OR ARE FORESEEABLE.
  %h2.tableTitle Business uses of our Services

  %p If you are using our Services on behalf of a business, that business accepts these terms. It will hold harmless and indemnify PCAP and its affiliates, officers, agents, and employees from any claim, suit or action arising from or related to the use of the Services or violation of these terms, including any liability or expense arising from claims, losses, damages, suits, judgments, litigation costs and attorneys’ fees.
  %h2.tableTitle About these Terms

  %p We may modify these terms or any additional terms that apply to a Service to, for example, reflect changes to the law or changes to our Services. You should look at the terms regularly. We’ll post notice of modifications to these terms on this page. We’ll post notice of modified additional terms in the applicable Service. Changes will not apply retroactively and will become effective no sooner than fourteen days after they are posted. However, changes addressing new functions for a Service or changes made for legal reasons will be effective immediately. If you do not agree to the modified terms for a Service, you should discontinue your use of that Service. If there is a conflict between these terms and the additional terms, the additional terms will control for that conflict. These terms control the relationship between PCAP and you. They do not create any third party beneficiary rights. If you do not comply with these terms, and we don’t take action right away, this doesn’t mean that we are giving up any rights that we may have (such as taking action in the future). If it turns out that a particular term is not enforceable, this will not affect any other terms. The laws of Minnesota, U.S.A., will apply to any disputes arising out of or relating to these terms or the Services. All claims arising out of or relating to these terms or the Services will be litigated exclusively in the federal or state courts of Hennepin County, Minnesota, USA, and you and PCAP consent to personal jurisdiction in those courts.

app/views/home/recipient_dashboard.html.haml
.container-full.dashboard
  .row
    = link_to users_path do
      .dashCell
        %span#icon.fa.fa-users{"aria-hidden" => "true"}
        .dashTitle
          %h4 Browse PCAs
    

app/views/home/reset_pass.html.haml
.container-full.vrtCntr
  %div.login-container
    %div.login-heading
      = image_tag("hct-logo4.png", class: "logoImg")
      -#%h3.form-signin-heading Homecare Timesheets
    =form_tag( reset_pass_post_path, method:"post", :class => "form-signin") do 
      = hidden_field_tag 'token', @token
      %p#alert= alert
      %div
        %p.log-title New Password
        %input#username.logform-control{:autofocus => "", :name => "password", :placeholder => "", :type => "password", :required => true}/
        %p.log-title Password Confirmation
        %input.logform-control{:name => "password_confirmation", :placeholder => "", :type => "password", :required => true}/
        #login-content.centered
          - if @errors.present? && @errors.any?
            #errors
              %ul
                - @errors.each do |message|
                  %li= message
        %button.btn-block{:type => "submit"} Submit
    .container.footer
  %p= "&copy #{Time.now.year} PCA Partners Inc.".html_safe

app/views/home/testpage.html.haml
%p &nbsp;