config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 post 'api/v1/login' => 'hcts_api#login', as: :hcts_api_login
 get 'api/v1/data' => 'hcts_api#get_data', as: :hcts_api_data
 post 'api/v1/create/sessiondata' => 'hcts_api#create_session_data', as: :hcts_api_create_session_data
 post 'api/v1/sessiondata/:id' => 'hcts_api#update_session_data', as: :hcts_api_update_session_data_post
 patch 'api/v1/sessiondata/:id' => 'hcts_api#update_session_data', as: :hcts_api_update_session_data_patch
 post 'api/v1/create/timesheet' => 'hcts_api#create_timesheet', as: :hcts_api_create_timesheet
 post 'api/v1/timesheet/:id' => 'hcts_api#update_timesheet', as: :hcts_api_update_timesheet_post
 patch 'api/v1/timesheet/:id' => 'hcts_api#update_timesheet', as: :hcts_api_update_timesheet_patch
 post 'api/v1/create/time/in' => 'hcts_api#create_time_in', as: :hcts_api_create_time_in
 post 'api/v1/timein/:id' => 'hcts_api#update_time_in', as: :hcts_api_update_time_in_post
 patch 'api/v1/timein/:id' => 'hcts_api#update_time_in', as: :hcts_api_update_time_in_patch
 post 'api/v1/create/time/out' => 'hcts_api#create_time_out', as: :hcts_api_create_time_out
 post 'api/v1/timeout/:id' => 'hcts_api#update_time_out', as: :hcts_api_update_time_out_post
 patch 'api/v1/timeout/:id' => 'hcts_api#update_time_out', as: :hcts_api_update_time_out_patch
 delete 'api/v1/careoptions/:id/delete' => 'hcts_api#empty_careoptions', as: :hcts_api_clear_careoptions
 post 'api/v1/careoptions' => 'hcts_api#set_careoptions', as: :hcts_api_set_careoptions
 post 'api/v1/create/files' => 'hcts_api#create_timesheet_files', as: :hcts_api_create_timesheet_files
 post 'api/v1/files/:id' => 'hcts_api#update_timesheet_files', as: :hcts_api_update_timesheet_files_post
 patch 'api/v1/files/:id' => 'hcts_api#update_timesheet_files', as: :hcts_api_update_timesheet_files_patch
 post 'api/v1/create/pca/signature' => 'hcts_api#create_pca_sign', as: :hcts_api_create_pca_sign
 post 'api/v1/recipientpassword' => 'hcts_api#verify_recipient_pass', as: :hcts_api_verify_recipient_pass
 post 'api/v1/create/recipient/signature' => 'hcts_api#create_recip_sign', as: :hcts_api_create_recip_sign
 post 'api/v1/finish/timesheets' => 'hcts_api#finish_timesheets', as: :hcts_api_finish_timesheets
 post 'api/v1/delete/timesheets' => 'hcts_api#delete_timesheets', as: :hcts_api_delete_timesheets
 get 'api/v1/pcas/:id' => 'hcts_api#get_pca', as: :hcts_api_get_pca
 get 'api/v1/counties' => 'hcts_api#get_counties', as: :hcts_api_get_counties
 get 'api/v1/qualifications' => 'hcts_api#get_qualifications', as: :hcts_api_get_qualifications
 post 'api/v1/devices' => 'hcts_api#set_device', as: :hcts_api_set_device
 post 'api/v1/requests' => 'hcts_api#set_request', as: :hcts_api_set_request
 get 'api/v1/requests/:id' => 'hcts_api#get_request', as: :hcts_api_get_request
 delete 'api/v1/requests/:id' => 'hcts_api#delete_request', as: :hcts_api_delete_request
 get 'api/v1/recipient/:id/requests' => 'hcts_api#get_requests_by_recipient', as: :hcts_api_get_requests_by_recipient
 get 'api/v1/pcas/:pca_id/available_requests' => 'hcts_api#get_available_requests', as: :hcts_api_get_available_requests
 get 'api/v1/pcas/:pca_id/accepted_requests' => 'hcts_api#get_accepted_requests', as: :hcts_api_get_accepted_requests
 post 'api/v1/pcas/:pca_id' => 'hcts_api#update_pca', as: :hcts_api_update_pca_post
 patch 'api/v1/pcas/:pca_id' => 'hcts_api#update_pca', as: :hcts_api_update_pca_patch
 post 'api/v1/pcas/:pca_id/image' => 'hcts_api#set_profile_image', as: :hcts_api_set_profile_image
 post 'api/v1/rsvps' => 'hcts_api#accept_request', as: :hcts_api_accept_request
 delete 'api/v1/rsvp/:rsvp_id' => 'hcts_api#decline_request', as: :hcts_api_decline_request
 get 'api/v1/pca/:pca_id/verify/:recipient_id' => 'hcts_api#need_verif', as: :hcts_api_check_verification
 post 'api/v1/verify/:verif_id' => 'hcts_api#verify', as: :hcts_api_verification_post
 patch 'api/v1/verify/:verif_id' => 'hcts_api#verify', as: :hcts_api_verification_patch
 post 'api/v1/verifcation/:verif_id/photo' => 'hcts_api#verification_photo', as: :hcts_api_verification_photo
 get 'api/v1/pca_contacts' => 'hcts_api#get_pca_contacts', as: :hcts_api_pca_contacts

 
 

 get 'recipient_dashboard' => 'home#recipient_dashboard', as: :recipient_dashboard
 get 'dashboard' => 'home#dashboard', as: :dashboard
 get 'privacy_policy' => 'home#privacy_policy', as: :privacy_policy
 get 'login' => 'home#login', as: :login
 post 'login' => 'home#login_post', as: :login_post
 get 'logout' => 'home#logout', as: :logout
 get 'sidebar-me' => 'home#testpage', as: :test_page
 get 'settings' => 'home#settings_redirect', as: :settings_redirect
 get 'users/archive/:id' => 'users#archive', as: :archive_user
 get 'users/dearchive/:id' => 'users#dearchive', as: :dearchive_user
 get 'agencies/:id/email' => 'agencies#email_settings', as: :agency_email_settings
 post 'agencies/:id/email' => 'agencies#email_submit', as: :agency_email_submit
 delete 'agencies/:agency_id/email/:id' => 'agencies#email_delete', as: :agency_email_delete
 get 'agencies/:id/subscription' => 'agencies#subscription', as: :agency_subscription_settings
 post 'agencies/:id/cancel_subscription' => 'agencies#cancel_subscription', as: :agency_cancel_subscription
 post 'agencies/:id/subscription' => 'agencies#subscription_submit', as: :agency_subscription_submit
 get 'agencies/:id/image' => 'agencies#get_image', as: :get_agency_image
 get 'assignments/' => 'assignments#index', as: :assignments
 get 'assignments/' => 'assignments#index', as: :assignments_index
 get 'assignments/new' => 'assignments#new', as: :new_assignment
 get 'assignments/:id/edit' => 'assignments#edit', as: :edit_assignment
 post 'assignments/new' => 'assignments#create', as: :recipient_pcas
 post 'assignments/:id/edit' => 'assignments#update', as: :update_assignment
 delete 'assignments/:id' => 'assignments#destroy', as: :destroy_assignment 
 get 'timesheets/get-zip' => 'timesheets#download_zip', as: :get_zip
 get 'timesheets/archive-all' => 'timesheets#archive_all', as: :archive_timesheets
 get 'timesheets/:id/archive' => 'timesheets#archive', as: :archive_timesheet
 get 'timesheets/:id/worker-sig' => 'timesheets#get_pca_sig', as: :get_pca_sig
 get 'timesheets/:id/recipient-sig' => 'timesheets#get_rec_sig', as: :get_rec_sig
 get 'timesheets/:id/download-pdf' => 'timesheets#download_pdf', as: :get_pdf
 get 'timesheets/:id/download-csv' => 'timesheets#download_csv', as: :get_csv
 get 'timesheets/:id/download-worker-sig' => 'timesheets#download_pca_sig', as: :download_pca_sig
 get 'timesheets/:id/download-recipient-sig' => 'timesheets#download_rec_sig', as: :download_rec_sig
 get 'verifications/:id/get-image' => 'verifications#get_image', as: :get_verif_image
 get 'get_time_in_form' => 'timesheets#get_time_in_form', as: :get_time_in_form

 get 'goals/' => 'goals#index', as: :goals_index
 get 'goals/new' => 'goals#new', as: :new_goal
 get 'goals/:id/edit' => 'goals#edit', as: :edit_goal
 post 'goals/new' => 'goals#create', as: :care_goals
 patch 'goals/:id' => 'goals#update', as: :care_goal
 get 'cares/' => 'care#index', as: :cares_index

 get 'users/:id/reset_pass' => 'users#reset_password', as: :reset_password
 post 'users/:id/reset_pass' => 'users#set_password', as: :set_password

 get 'forgot' => 'home#forgot', as: :forgot
 post 'forgot' => 'home#forgot_post', as: :forgot_post
 get 'reset' => 'home#reset_pass', as: :reset_pass
 post 'reset' => 'home#reset_pass_post', as: :reset_pass_post


  resources :verifications
  resources :timesheets
  resources :recipients
  resources :pcas
  resources :agencies
  resources :users
 get 'sign-up' => 'home#signup', as: :sign_up
 root 'home#login'


end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  before_action :set_agency, only: [:show, :edit, :update, :destroy, :email_settings, :email_submit, :email_delete, :get_image, :subscription, :cancel_subscription, :subscription_submit]
  skip_before_action :set_current_user, only: [:new, :create]

  # GET /agencies
  # GET /agencies.json
  def index
    if @current_user.is_admin?
      session[:current_agency_id] = nil
      @agencies = Agency.all
    else
      redirect_to users_path, alert: "Unauthorized"
    end
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
    if @current_user.is_admin?
      session[:current_agency_id] = params[:id]
      redirect_to dashboard_path
    else
      redirect_to users_path, alert: "Unauthorized"
    end

  end

  # GET /agencies/new
  def new
    @agency = Agency.new
    @agency.users.new
  end

  # GET /agencies/1/edit
  def edit
  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(agency_params)
    a_params = params[:agency]
    if a_params[:accept_terms].present?        
      if @agency.save
        if @agency.set_source_subscription(params[:subscription], params[:stripeToken])
          @user = @agency.users.first
          if @user.present?
            @user.last_login = DateTime.now
            @user.save
            @current_user = @user
            session[:current_user_id] = @user.id
            redirect_to dashboard_path, notice: 'Successfully signed up'
          else
            redirect_to root_path, notice: 'Please contact support'            
          end
        else
          redirect_to root_path, notice: 'Please contact support'            
        end
      else
        render :new
      end
    else
      @agency.errors.add(:base, :invalid, message:"Terms must be accepted")
      render :new
    end
  end

  # PATCH/PUT /agencies/1
  # PATCH/PUT /agencies/1.json
  def update
    respond_to do |format|
      if @agency.update(agency_params)
        format.html { redirect_to edit_agency_path(@agency), notice: 'Agency was successfully updated.' }
        format.json { render :show, status: :ok, location: @agency }
      else
        format.html { render :edit }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    @agency.destroy
    respond_to do |format|
      format.html { redirect_to agencies_url, notice: 'Agency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def email_settings
    @email_setting = @agency.email_settings.build
    @email_settings = Agency.find_by(id:@agency.id).email_settings

  end

  def email_submit
    @email_setting = EmailSetting.new(email_params)
    if @email_setting.save
      redirect_to agency_email_settings_path(@agency)
    else
      render 'email_settings'
    end
  end
  
  def email_delete
    @email_setting = EmailSetting.find_by(id:params[:id])
    if @email_setting.destroy
      redirect_to agency_email_settings_path(@agency)
    else
      render 'email_settings'
    end
  end

  def subscription
    source = @agency.get_source
    @subscription_name = @agency.subscription_name    
    if source.present?
      @card = source.sources.data.first
    end   
  end

  def cancel_subscription
    @subscriptions = @agency.get_subscriptions
    if @subscriptions.present?
      @subscriptions.each do |sub|
        @agency.cancel_subscription(sub.id)
      end
    end
    redirect_to agency_subscription_settings_path(@agency), notice: "Subscription Cancelled" 
  end


  def subscription_submit
    if params.has_key?("subscription") || params.has_key?("stripeToken")
      source = @agency.get_source
      if params[:subscription].present?
        if @agency.subscription_name != params[:subscription]
          @subscriptions = @agency.get_subscriptions
          if @subscriptions.present?
            @subscriptions.each do |sub|
              if sub.plan.name != params[:subscription]
                @agency.cancel_subscription(sub.id)
              end
            end
          end 
          if !@agency.get_subscriptions.present?
            create_sub = @agency.create_subscription(params[:subscription])
          end
          if create_sub.present?
            redirect_to agency_subscription_settings_url(@agency), notice: "Subscription Updated"
          else
            @subscription_name = @agency.subscription_name    
            if source.present?
              @card = source.sources.data.first
            end 
            render 'subscription', alert: "Error 1"
          end
        else
          redirect_to agency_subscription_settings_url(@agency), notice: "Subscription Updated"
        end
     elsif params[:stripeToken].present?
       update_card = @agency.replace_card(params[:stripeToken])
       if update_card
         redirect_to agency_subscription_settings_url(@agency), notice: "Card Updated"
       else
        if source.present?
          @card = source.sources.data.first
        end
        render 'subscription', alert: "Error 2"
       end 
      else
        @subscription_name = @agency.subscription_name    
        if source.present?
          @card = source.sources.data.first
        end 
        render 'subscription', alert: "Error 3"
      end
    else
      @subscription_name = @agency.subscription_name    
      if source.present?
        @card = source.sources.data.first
      end 
      render 'subscription', alert: "Error"
    end
  end


  def get_image
    @img_arr = @agency.get_image
    if @img_arr.present?
      data = open(@img_arr[0])
      send_data data.read, filename: @img_arr[1], type: @img_arr[2]
    else
      render json: {errors:"No file set"}, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      if params.has_key?(:id)
        @agency = Agency.find(params[:id])
      elsif params.has_key?(:agency_id)
        @agency = Agency.find_by(id:params[:agency_id])
      elsif @current_user.is_admin?
        @agency = Agency.find_by(id:session[:current_agency_id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agency_params
      the_params = params.require(:agency).permit(:agency_name, :state_id, :week_start_date, :start_time, :phoneNumber, :imageName, :image, :pca_finder_active, :users_attributes => [:id, :firstName, :lastName, :username, :email, :password, :password_confirmation, :roles])
      
      if @current_user.is_admin?
        return the_params
      end
      
      the_params.except(:pca_finder_active)
    end

    def email_params
      params.require(:email_setting).permit(:email, :agency_id)
    end


end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/views/agencies/_form.html.haml
- is_new = action_name == "new" || action_name == "create"
= form_for @agency do |f|
  %div.container-full.grid-container.formBox.panel-back
    - if is_new
      %table.uncommon
        - if @agency.errors.any?
          %tr
            %td#errors{colspan:"2"}
              %h2= "#{pluralize(@agency.errors.count, "error")} prohibited this agency from being saved:"
              %ul
                - @agency.errors.full_messages.each do |message|
                  %li= message
        %tr
          %td.fieldTitle Agency Name
          %td.field= f.text_field :agency_name
        %tr
          %td.fieldTitle Phone Number
          %td.field= f.text_field :phoneNumber
        %tr
          %td.fieldTitle State
          %td.field= f.collection_select :state_id, State.all, :id, :name
        %tr
          %td{colspan:"2"}
            %h2.tableTitle Agency User Info
        = f.fields_for :users do |u|
          = u.hidden_field :roles, value:User::ROLES[1]
          %tr
            %td.fieldTitle First Name
            %td.field= u.text_field :firstName
          %tr
            %td.fieldTitle Last Name
            %td.field= u.text_field :lastName
          %tr
            %td.fieldTitle Username
            %td.field= u.text_field :username
          %tr
            %td.fieldTitle Email
            %td.field= u.email_field :email 
          %tr
            %td.fieldTitle Password
            %td.field= u.password_field :password
          %tr
            %td.fieldTitle Verify Password
            %td.field= u.password_field :password_confirmation
        %tr
          %td{colspan:"2"}
            %h2.tableTitle Agency User Info
        %tr
          %td.fieldTitle Subscription
          %td.field 
            - ss = StripeService.new
            = select_tag "subscription", options_for_select(ss.get_plan_names.prepend("No Active Subscription"), selected:@agency.subscription_name, disabled:["No Active Subscription"])
        %tr
          %td.fieldTitle Card Info
          %td.field
            %div#card-element
        %tr
          %td.field{colspan:"2"}
            .bordered.right-margin
              Accept Terms
              = f.check_box :accept_terms
            = link_to "Terms and Conditions", privacy_policy_path, {class:'current'}
        %tr
          %td.field{colspan:"2"}
            %div#card-errors{role:"alert"}
        %tr
          %td.actions{colspan:"2"}= f.submit 'Sign Up', data: { disable_with: false}, id:"new_sub" 
    - else
      %table.uncommon
        %tr
          %td{colspan:"3"}
            .left-filter
              %span.active Agency Settings
              %span &middot;
              = link_to "Email Settings", agency_email_settings_path(@agency)
              %span &middot;
              = link_to "Subscription", agency_subscription_settings_path(@agency)
        - if @agency.errors.any?
          %tr
            %td#errors{colspan:"3"}
              %h2= "#{pluralize(@agency.errors.count, "error")} prohibited this agency from being saved:"
              %ul
                - @agency.errors.full_messages.each do |message|
                  %li= message
        %tr
          %td.fieldTitle Agency Name
          %td.field= f.text_field :agency_name
          %td.agentcPic{rowspan:"6",style:"vertical-align:top"}
            %p Current Image
            = image_tag(@agency.get_image_url,width:100)
        %tr
          %td.fieldTitle Phone Number
          %td.field= f.text_field :phoneNumber
        %tr
          %td.fieldTitle State
          %td.field= f.collection_select :state_id, State.all, :id, :name
        %tr
          %td.fieldTitle Image
          %td.field= f.file_field :image
        %tr
          %td.fieldTitle
            Week Start Date
          %td.field
            = f.select :week_start_date, Date::DAYNAMES
            %br
            %span.cpy{style:"cursor:inherit"} Changes will effect your workers total hours worked for the past week
        %tr
          %td.fieldTitle
            Start Time
            %br
            %span.cpy &nbsp;
          %td.field
            = f.select :start_time, Agency::START_TIMES
            %br
            %span.cpy{style:"cursor:inherit"} Changes will effect your workers total hours worked for the past week
        - if @current_user.is_admin?
          %tr
            %td.fieldTitle PCA Finder Active?
            %td.field= f.check_box :pca_finder_active
        %tr
          %td.actions{colspan:"3"}
            = link_to 'Cancel', url_for(:back)
            = f.submit 'Save'

app/views/agencies/edit.html.haml
- @page_title = @agency.name
- @partial = true
= render 'form'

app/views/agencies/email_settings.html.haml
- @page_title = @agency.name
- @partial = true
= form_for @email_setting, url: agency_email_submit_path, method: 'post' do |f|
  = f.hidden_field :agency_id
  %div.container-full.grid-container.formBox.panel-back
    %table.uncommon
      %tr
        %td{colspan:"2"}
          .left-filter
            = link_to "Agency Settings", edit_agency_path(@agency)
            %span &middot;
            %span.active Email Settings
            %span &middot;
            = link_to "Subscription", agency_subscription_settings_path(@agency)
      %tr
        %td{style:"width:75%"}
          %table.uncommon
            %tr
              %td.fieldTitle Email
              %td.field= f.email_field :email 
            %tr
              %td.actions{colspan:"2"}= f.submit "Save"
            - if @email_setting.errors.any?
              %tr
                %td{colspan:"2"}
                  #errors
                    %ul
                      - @email_setting.errors.full_messages.each do |message|
                        %li= message
        %td
          %p.warning Any emails you enter into this form will get emailed a pdf and csv file of every time entry that gets completed.
      %tr
        %td
          %table.uncommon
            %tr
              %th Current Email Addresses
              %th Remove
            - @email_settings.each do |email_setting|
              %tr
                %td= email_setting.email
                %td{style:"width:5%"}= link_to "&#x2716;".html_safe, agency_email_delete_path(email_setting,agency_id:@agency.id), data: {confirm: "Are you sure?" }

app/views/agencies/index.html.haml
- @page_title = "Agencies"
%div.users.container-full.grid-container
  %table.fullTable.col-12.table-shadow
    %thead
      %tr
        %th Agency name
        %th State
        %th Week Start Day/Time
        %th Phone
        %th Plan

    %tbody
      - @agencies.each do |agency|
        %tr
          %td= link_to agency.name, agency
          %td= agency.state.name
          %td= "#{agency.week_start_date} #{agency.start_time}"
          %td= agency.phoneNumber.present? ? number_to_phone(agency.phoneNumber,area_code:true) : ""
          %td= agency.stripe_sub_name

app/views/agencies/new.html.haml
%h1.pageTitle-partials Agency Sign Up
= render 'form'

app/views/agencies/show.html.haml
%h1.pageTitle= "Details:   #{@agency.name}"
%p.left-filter.lShift
  = link_to 'Edit', edit_agency_path(@agency)
  %span &middot;
  = link_to 'Agency Admin', users_path(agency_id:@agency.id)
  %span &middot;
  = link_to 'Back', agencies_path
%div.showFrame
  %table
    .half
      = image_tag Agency.get_image(@agency.imageName), :class => "shoImage"
  %table.half.table.shoTable
    %thead{colspan:"3"}
      %tr
        %th Agency name:
        %td= @agency.agency_name
      %tr
        %th State:
        %td= @agency.state.name
      %tr
        %th Week Start:
        %td= "#{@agency.week_start_date} #{@agency.start_time}"
      %tr
        %th Phonenumber:
        %td= number_to_phone(@agency.phoneNumber,area_code:true)
      %tr
        %th Plan:
        %td= @agency.plan

app/views/agencies/subscription.html.haml
- @page_title = @agency.name
- @partial = true
%div.container-full.grid-container.formBox.panel-back
  %table.uncommon
    %tr
      %td{colspan:2}
        .left-filter
          = link_to "Agency Settings", edit_agency_path(@agency)
          %span &middot;
          = link_to "Email Settings", agency_email_settings_path(@agency)
          %span &middot;
          %span.active Subscription
    %tr
      %td.fieldTitle Subscription:
      %td.field= @subscription_name 
    %tr
      %td.fieldTitle Card Last 4
      %td.field= @card.present? ? @card.last4 : "----"
    %tr
      %td.fieldTitle Expires
      %td.field= @card.present? ? "#{@card.exp_month}/#{@card.exp_year}" : "--/----"
    %tr#sub_change
      %td{colspan:"2",style:"text-align:center;"}
        .btnFrame#changeSub{onclick:"changeSubscription(true)", style:"float:none;margin:0 auto;"}
          %p#changeP Change Subscription
    %tr#change_sub.collapse
      %td{colspan:"2"}
        - if @agency.subscription_name != "No Active Subscription"
          .form-row{style:"margin:0 auto 15px;"}= link_to "Cancel Subscription", agency_cancel_subscription_path(@agency), method: :post, data: { confirm: 'Are you sure?' }
        %form{action:agency_subscription_submit_path, method:"post", id:"sub-form"}
          = hidden_field_tag "authenticity_token", form_authenticity_token
          .form-row
            %label{for:"subscription"} Subscription
            .field
              - ss = StripeService.new
              = select_tag "subscription", options_for_select(ss.get_plan_names.prepend("No Active Subscription"), selected:@agency.subscription_name, disabled:["No Active Subscription"]) 
          .form-row
            %div#sub-errors{role:"alert"}
            %div.actions
              %a{onclick:"changeSubscription(false);"} Cancel
              %input{type:"submit",value:"Submit"}
    %tr#card_change
      %td{colspan:"2",style:"text-align:center;"}
        .btnFrame#changeCard{onclick:"changeCard(true)", style:"float:none;margin:0 auto;"}
          %p#changeC Change Card
    %tr#change_card.collapse
      %td{colspan:"2"}
        %form{action:agency_subscription_submit_path, method:"post", id:"payment-form"}
          = hidden_field_tag "authenticity_token", form_authenticity_token
          .form-row
            %label{for:"card-element"} Credit or debit card
            %div#card-element
            %div#card-errors{role:"alert"}
            %div.actions
              %a{onclick:"changeCard(false)"} Cancel 
              %input{type:"submit",value:"Submit"}