config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 post 'api/v1/login' => 'hcts_api#login', as: :hcts_api_login
 get 'api/v1/data' => 'hcts_api#get_data', as: :hcts_api_data
 post 'api/v1/create/sessiondata' => 'hcts_api#create_session_data', as: :hcts_api_create_session_data
 post 'api/v1/sessiondata/:id' => 'hcts_api#update_session_data', as: :hcts_api_update_session_data_post
 patch 'api/v1/sessiondata/:id' => 'hcts_api#update_session_data', as: :hcts_api_update_session_data_patch
 post 'api/v1/create/timesheet' => 'hcts_api#create_timesheet', as: :hcts_api_create_timesheet
 post 'api/v1/timesheet/:id' => 'hcts_api#update_timesheet', as: :hcts_api_update_timesheet_post
 patch 'api/v1/timesheet/:id' => 'hcts_api#update_timesheet', as: :hcts_api_update_timesheet_patch
 post 'api/v1/create/time/in' => 'hcts_api#create_time_in', as: :hcts_api_create_time_in
 post 'api/v1/timein/:id' => 'hcts_api#update_time_in', as: :hcts_api_update_time_in_post
 patch 'api/v1/timein/:id' => 'hcts_api#update_time_in', as: :hcts_api_update_time_in_patch
 post 'api/v1/create/time/out' => 'hcts_api#create_time_out', as: :hcts_api_create_time_out
 post 'api/v1/timeout/:id' => 'hcts_api#update_time_out', as: :hcts_api_update_time_out_post
 patch 'api/v1/timeout/:id' => 'hcts_api#update_time_out', as: :hcts_api_update_time_out_patch
 delete 'api/v1/careoptions/:id/delete' => 'hcts_api#empty_careoptions', as: :hcts_api_clear_careoptions
 post 'api/v1/careoptions' => 'hcts_api#set_careoptions', as: :hcts_api_set_careoptions
 post 'api/v1/create/files' => 'hcts_api#create_timesheet_files', as: :hcts_api_create_timesheet_files
 post 'api/v1/files/:id' => 'hcts_api#update_timesheet_files', as: :hcts_api_update_timesheet_files_post
 patch 'api/v1/files/:id' => 'hcts_api#update_timesheet_files', as: :hcts_api_update_timesheet_files_patch
 post 'api/v1/create/pca/signature' => 'hcts_api#create_pca_sign', as: :hcts_api_create_pca_sign
 post 'api/v1/recipientpassword' => 'hcts_api#verify_recipient_pass', as: :hcts_api_verify_recipient_pass
 post 'api/v1/create/recipient/signature' => 'hcts_api#create_recip_sign', as: :hcts_api_create_recip_sign
 post 'api/v1/finish/timesheets' => 'hcts_api#finish_timesheets', as: :hcts_api_finish_timesheets
 post 'api/v1/delete/timesheets' => 'hcts_api#delete_timesheets', as: :hcts_api_delete_timesheets
 get 'api/v1/pcas/:id' => 'hcts_api#get_pca', as: :hcts_api_get_pca
 get 'api/v1/counties' => 'hcts_api#get_counties', as: :hcts_api_get_counties
 get 'api/v1/qualifications' => 'hcts_api#get_qualifications', as: :hcts_api_get_qualifications
 post 'api/v1/devices' => 'hcts_api#set_device', as: :hcts_api_set_device
 post 'api/v1/requests' => 'hcts_api#set_request', as: :hcts_api_set_request
 get 'api/v1/requests/:id' => 'hcts_api#get_request', as: :hcts_api_get_request
 delete 'api/v1/requests/:id' => 'hcts_api#delete_request', as: :hcts_api_delete_request
 get 'api/v1/recipient/:id/requests' => 'hcts_api#get_requests_by_recipient', as: :hcts_api_get_requests_by_recipient
 get 'api/v1/pcas/:pca_id/available_requests' => 'hcts_api#get_available_requests', as: :hcts_api_get_available_requests
 get 'api/v1/pcas/:pca_id/accepted_requests' => 'hcts_api#get_accepted_requests', as: :hcts_api_get_accepted_requests
 post 'api/v1/pcas/:pca_id' => 'hcts_api#update_pca', as: :hcts_api_update_pca_post
 patch 'api/v1/pcas/:pca_id' => 'hcts_api#update_pca', as: :hcts_api_update_pca_patch
 post 'api/v1/pcas/:pca_id/image' => 'hcts_api#set_profile_image', as: :hcts_api_set_profile_image
 post 'api/v1/rsvps' => 'hcts_api#accept_request', as: :hcts_api_accept_request
 delete 'api/v1/rsvp/:rsvp_id' => 'hcts_api#decline_request', as: :hcts_api_decline_request
 get 'api/v1/pca/:pca_id/verify/:recipient_id' => 'hcts_api#need_verif', as: :hcts_api_check_verification
 post 'api/v1/verify/:verif_id' => 'hcts_api#verify', as: :hcts_api_verification_post
 patch 'api/v1/verify/:verif_id' => 'hcts_api#verify', as: :hcts_api_verification_patch
 post 'api/v1/verifcation/:verif_id/photo' => 'hcts_api#verification_photo', as: :hcts_api_verification_photo
 get 'api/v1/pca_contacts' => 'hcts_api#get_pca_contacts', as: :hcts_api_pca_contacts

 
 

 get 'recipient_dashboard' => 'home#recipient_dashboard', as: :recipient_dashboard
 get 'dashboard' => 'home#dashboard', as: :dashboard
 get 'privacy_policy' => 'home#privacy_policy', as: :privacy_policy
 get 'login' => 'home#login', as: :login
 post 'login' => 'home#login_post', as: :login_post
 get 'logout' => 'home#logout', as: :logout
 get 'sidebar-me' => 'home#testpage', as: :test_page
 get 'settings' => 'home#settings_redirect', as: :settings_redirect
 get 'users/archive/:id' => 'users#archive', as: :archive_user
 get 'users/dearchive/:id' => 'users#dearchive', as: :dearchive_user
 get 'agencies/:id/email' => 'agencies#email_settings', as: :agency_email_settings
 post 'agencies/:id/email' => 'agencies#email_submit', as: :agency_email_submit
 delete 'agencies/:agency_id/email/:id' => 'agencies#email_delete', as: :agency_email_delete
 get 'agencies/:id/subscription' => 'agencies#subscription', as: :agency_subscription_settings
 post 'agencies/:id/cancel_subscription' => 'agencies#cancel_subscription', as: :agency_cancel_subscription
 post 'agencies/:id/subscription' => 'agencies#subscription_submit', as: :agency_subscription_submit
 get 'agencies/:id/image' => 'agencies#get_image', as: :get_agency_image
 get 'assignments/' => 'assignments#index', as: :assignments
 get 'assignments/' => 'assignments#index', as: :assignments_index
 get 'assignments/new' => 'assignments#new', as: :new_assignment
 get 'assignments/:id/edit' => 'assignments#edit', as: :edit_assignment
 post 'assignments/new' => 'assignments#create', as: :recipient_pcas
 post 'assignments/:id/edit' => 'assignments#update', as: :update_assignment
 delete 'assignments/:id' => 'assignments#destroy', as: :destroy_assignment 
 get 'timesheets/get-zip' => 'timesheets#download_zip', as: :get_zip
 get 'timesheets/archive-all' => 'timesheets#archive_all', as: :archive_timesheets
 get 'timesheets/:id/archive' => 'timesheets#archive', as: :archive_timesheet
 get 'timesheets/:id/worker-sig' => 'timesheets#get_pca_sig', as: :get_pca_sig
 get 'timesheets/:id/recipient-sig' => 'timesheets#get_rec_sig', as: :get_rec_sig
 get 'timesheets/:id/download-pdf' => 'timesheets#download_pdf', as: :get_pdf
 get 'timesheets/:id/download-csv' => 'timesheets#download_csv', as: :get_csv
 get 'timesheets/:id/download-worker-sig' => 'timesheets#download_pca_sig', as: :download_pca_sig
 get 'timesheets/:id/download-recipient-sig' => 'timesheets#download_rec_sig', as: :download_rec_sig
 get 'verifications/:id/get-image' => 'verifications#get_image', as: :get_verif_image
 get 'get_time_in_form' => 'timesheets#get_time_in_form', as: :get_time_in_form

 get 'goals/' => 'goals#index', as: :goals_index
 get 'goals/new' => 'goals#new', as: :new_goal
 get 'goals/:id/edit' => 'goals#edit', as: :edit_goal
 post 'goals/new' => 'goals#create', as: :care_goals
 patch 'goals/:id' => 'goals#update', as: :care_goal
 get 'cares/' => 'care#index', as: :cares_index

 get 'users/:id/reset_pass' => 'users#reset_password', as: :reset_password
 post 'users/:id/reset_pass' => 'users#set_password', as: :set_password

 get 'forgot' => 'home#forgot', as: :forgot
 post 'forgot' => 'home#forgot_post', as: :forgot_post
 get 'reset' => 'home#reset_pass', as: :reset_pass
 post 'reset' => 'home#reset_pass_post', as: :reset_pass_post


  resources :verifications
  resources :timesheets
  resources :recipients
  resources :pcas
  resources :agencies
  resources :users
 get 'sign-up' => 'home#signup', as: :sign_up
 root 'home#login'


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :archive, :dearchive, :reset_password, :set_password]
  before_action :set_agencies, only: [:new, :create, :edit, :update]
  before_action :set_agency, only: [:index, :new, :create, :edit, :update]

  # GET /users
  # GET /users.json
  def index
    
    if @current_user.is_recipient?
      @agency = @current_user.get_agency
      @users = @agency.pcas
      @page_title = "All PCAs"
      if params.has_key?(:gender)
        @users = @users.where(gender: params[:gender])
        case params[:gender]
        when "1"
          @page_title = "Female PCAs"
        when "2"
          @page_title = "Male PCAs"
        else
          @page_title = "PCAs"
        end
      end
      
      if params.has_key?(:q)
        @page_title = "Results for #{params[:q]}"
        # Search should go through name and address fields
        @our_pcas = []
        
        @users.each do |pca|
          if (pca.firstName.present? && pca.firstName.include?(params[:q])) || (pca.lastName.present? && pca.lastName.include?(params[:q])) || (pca.homeAddress.present? && pca.homeAddress.include?(params[:q]))
            @our_pcas << pca.id
          end
        end
        
        @users = @agency.pcas.where(id: @our_pcas)
      end
      
      @users = @users.get_users
      
    else # Logic for a non-recipient user
      if params.has_key?("archived") && params[:archived] == "true"
        @archived = true
      else
        @archived = false
      end
      if @agency.present?
        @users = []
        if @agency.present? && !@archived
          if params.has_key?("admins")
            @users = User.nonarchived.where("roles like '%ADMIN%'")
            @admins =  true
          elsif params.has_key?("pcas")
            @users = @agency.pcas.get_users
            @pcas = true
          elsif params.has_key?("agents")
            @users = @agency.users.nonarchived
            @agents = true
          else
            @users = @agency.recipients.get_users
            @recips = true
          end
        elsif @current_user.is_admin?
          if params.has_key?("admins")
            @users = User.archived.where("roles like '%ADMIN%'")
            @admins =  true
          elsif params.has_key?("pcas")
            @users = @agency.pcas.get_archived_users
            @pcas = true
          elsif params.has_key?("agents")
            @users = @agency.users.archived
            @agents = true
          else
            @users = @agency.recipients.get_archived_users
            @recips = true
          end
        end
      else
        if !@archived
          if params.has_key?("admins")
            @users = User.nonarchived.where("roles like '%ADMIN%'")
            @admins =  true
          elsif params.has_key?("pcas")
            @users = Pca.all.get_users
            @pcas = true
          elsif params.has_key?("agents")
            @users = User.nonarchived.where.not(agency_id:nil)
            @agents = true
          else
            @users = Recipient.all.get_users
            @recips = true
          end
        else
          if params.has_key?("admins")
            @users = User.archived.where("roles like '%ADMIN%'")
            @admins =  true
          elsif params.has_key?("pcas")
            @users = Pca.all.get_archived_users
            @pcas = true
          elsif params.has_key?("agents")
            @users = User.archived.where.not(agency_id:nil)
            @agents = true
          else
            @users = Recipient.all.get_archived_users
            @recips = true
          end
        end
      end
    end
    
    @limit = 10
    @count = @users.count
    if params.has_key?("page")
      @page = Integer(params[:page]) rescue 1
    else
      @page = 1
    end 
    offset = (@page - 1) * @limit
    @users = @users.limit(@limit).offset(offset)
  end

  # GET /users/1
  # GET /users/1.json
  def show
   # if @current_user.agency.present?
   #   redirect_to @current_user.agency
   # end
  end

  # GET /users/new
  def new
    if params.has_key?("admin") && @current_user.is_admin?
      @user = User.new(roles:User::ADMIN_ROLE)
    else
      @user = User.new
    end
  end

  # GET /users/1/edit
  def edit
    @user.roles = User::AGENCY_ROLE
    if @current_user.is_admin?
      @roles = @user.roles
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.roles = User::AGENCY_ROLE
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def archive
    agency = get_agency(@user)
    @user.update(archived:true)
    if @user.is_pca?
      @user.pca.timesheets.update_all(archived:true)
    end
    if @user.is_recipient?
      @user.recipient.timesheets.update_all(archived:true)
    end
    redirect_to request.referrer
  end


  def dearchive
    agency = get_agency(@user)
    @user.update(archived:false)
    redirect_to request.referrer
  end

  def reset_password
  end

  def set_password
    errors = []
    if @user.present?
      is_pca = @user.is_pca?
      is_recip = @user.is_recipient?
      is_agent = @user.is_agent?
      change_user = false
      # @current_user.is_agent? || @current_user == @user || (params.has_key?("current_password") && @user.authorize_password(params[:current_password]))
      if @current_user.is_agent? || @current_user.is_admin?
        change_user = true
      elsif @user == @current_user
        change_user = true
      elsif params.has_key?("current_password") && @user.authorize_password(params[:current_password])
        change_user = true
      end
      logger.debug("Change User: #{change_user}")
      if change_user
        if @user.update(user_params) 
          if @current_user.is_agent? || @current_user.is_admin?
            if is_agent
              redirect_to users_path(agents:true), notice: "Password successfully changed"
            elsif is_pca
              redirect_to users_path(pcas:true), notice: "Password successfully changed"
            elsif is_recip
              redirect_to users_path(recipients:true), notice: "Password successfully changed"
            else
              redirect_to users_path, notice: "Password successfully changed"
            end
          elsif @current_user == @user
            if @user.is_pca?
              redirect_to edit_pca_path(@user.pca), notice: "Password successfully changed"
            elsif @user.is_recipient?
              redirect_to edit_recipient_path(@user.recipient), notice: "Password successfully changed"
            elsif @user.is_agent?
              redirect_to users_path(agents:true), notice: "Password successfully changed"
            end
          end
        else
          render 'reset_password'
        end
      else
        redirect_to users_path, notice: "Unauthorized" 
      end
    else
      render 'reset_password'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def set_agencies
      if @current_user.is_agent?
        @agencies = Agency.where(id: @current_user.agency_id)
      else
        @agencies = Agency.all
      end
    end

    def set_agency
      if params.has_key?("agency_id")
        @agency = Agency.find_by(id:params[:agency_id])
      end
      if @agency.nil?
        if @current_user.is_admin?
          @agency = Agency.find_by(id:session[:current_agency_id])
        else
          @agency = @current_user.agency
        end
      end
    end

    def get_agency(user)
      if user.is_agent?
        return user.agency
      elsif user.is_recipient?
        return user.recipient.agency
      elsif user.is_pca?
        return user.pca.agency
      elsif user.is_admin?
        return nil
      else
        return @current_user.agency
      end
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:agency_id, :admin_id, :username, :email, :enabled, :password, :password_confirmation, :locked, :expired, :roles, :firstName, :lastName, :current_password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/partials/_default_index.html.haml
- @page_title = "Users"
%div.users.container-full.grid-container
  %table.fullTable.col-12.table-shadow
    %thead
      %tr
        %th{colspan:"7"}
          .left-filter.lShare
            - if @recips.present?
              %span.active Recipients
            - else
              - if @archived
                = link_to "Recipients", users_path(recipients:true, archived:true)
              - else
                = link_to "Recipients", users_path(recipients:true)
            %span &middot;
            - if @pcas.present?
              %span.active Workers
            - else
              - if @archived
                = link_to "Workers", users_path(pcas:true, archived:true)
              - else
                = link_to "Workers", users_path(pcas:true)
            %span &middot;
            - if @agents.present?
              %span.active Agency Users
            - else
              - if @archived
                = link_to "Agency Users", users_path(agents:true, archived:true)  
              - else
                = link_to "Agency Users", users_path(agents:true)
            - if @current_user.is_admin?
              %span &middot;
              - if @admins.present?
                %span.active Site Admin
              - else
                - if @archived
                  = link_to "Site Admin", users_path(admins:true, archived:true)
                - else
                  = link_to "Site Admin", users_path(admins:true) 
              %span &middot
              - if params.has_key?("archived")
                = link_to "Unarchived", request.parameters.except(:archived)
              - else
                = link_to "Archived", request.parameters.merge(archived:true) 
          .right-filter.rShare.btnFrame
            - if @agency.present?
              - if @recips.present?
                %p= link_to "New Recipient", new_recipient_path(agency_id:@agency.id)
              - elsif @agents.present?
                %p= link_to "New Agency User", new_user_path(agency_id:@agency.id)
              - elsif @pcas.present?
                %p= link_to "New Worker", new_pca_path(agency_id:@agency.id)
            - else
              - if @recips.present?
                %p= link_to "New Recipient", new_recipient_path
              - elsif @agents.present?
                %p= link_to "New Agency User", new_user_path
              - elsif @pcas.present?
                %p= link_to "New Worker", new_pca_path
              - elsif @admins.present?
                %p= link_to "New Admin", new_user_path(admin:true)
      %tr
        %th{colspan:"7"}
          %hr
      %tr
        %th.userCell Name
        %th.userCell Username
        %th.userCell Agency
        %th.longAddress Email
        %th.userCell Last Login
        %th.thin 
        %th.thin 
    %tbody
      - @users.each do |user|
        %tr
          - if user.is_agent?
            %td.userCell= user.name
          - elsif user.is_pca?
            %td.userCell= user.pca.name
          - elsif user.is_recipient?
            %td.userCell= user.recipient.name
          - else
            %td.userCell= user.name
          %td.userCell= user.username
          %td.userCell
            - if @current_user.is_admin?
              - if user.is_pca?
                = link_to user.pca.agency.name, user.pca.agency
              - elsif user.is_recipient?
                = link_to user.recipient.agency.name, user.recipient.agency
              - elsif user.agency.present?
                = link_to user.agency.name, user.agency
            - else
              - if user.is_pca?
                = user.pca.agency.name
              - elsif user.is_recipient?
                = user.recipient.agency.name
              - else
                = user.agency.name
          %td.longAddress{title:"#{user.email}"}= user.email
          %td.userCell= user.last_login.present? ? user.last_login.strftime("%D, %I:%M%P") : "-"
          %td.thin
            - if user.is_agent? || user.is_admin?
              = link_to edit_user_path(user) do
                %i.fa.fa-pencil{"aria-hidden" => "true", "style" => "font-size: 1.5em"}
            - elsif user.is_recipient?
              = link_to edit_recipient_path(user.recipient) do
                %i.fa.fa-pencil{"aria-hidden" => "true", "style" => "font-size: 1.5em"}
            - elsif user.is_pca?
              = link_to edit_pca_path(user.pca) do
                %i.fa.fa-pencil{"aria-hidden" => "true", "style" => "font-size: 1.5em"}
          %td.thin
            - if @archived
              = link_to "&#x2716;".html_safe, dearchive_user_path(user), data: {confirm: "Dearchived users will be shown, but this will not dearchive the user's time entries. Are you sure you want to dearchive this user?" }
            - else
              = link_to "&#x2716;".html_safe, archive_user_path(user), data: {confirm: "Archived users will not be shown. Are you sure you want to archive this user?" }
      - if @count > @limit
        - link_count = 0
        - link_total = (@count/@limit.to_f).ceil
        %tr
          %td.page-links{colspan:"7"}
            %div
              - page_count = @page - 2 > 0 && link_total > 5 ? @page - 2 : 1
              - loop do
                - link_count += 1 
                - if page_count > 1 && link_count == 1 && link_total > 5
                  = link_to "&#171;".html_safe, request.parameters.merge(page:page_count), class:"page_link"
                - elsif link_count == 5 && link_total > 5
                  = link_to "&#187;".html_safe, request.parameters.merge(page:page_count), class:"page_link"
                - else
                  - if page_count == @page
                    = link_to "#{page_count}", request.parameters.merge(page:page_count), class:"page-link current"
                  - else
                    = link_to "#{page_count}", request.parameters.merge(page:page_count), class:"page-link"
                - break if (page_count * @limit > @count) || link_count > 4
                - page_count += 1

app/views/users/partials/_default_show.html.haml
default show
- @page_title = "About: #{@user.name}"
%div.showFrame
  %table.shoTable.uncommon
    %tbody
      %tr
        %td{colspan:"2",style:"text-align:center"}
          .left-filter
            = link_to "Agency Users", users_path(admins:true)
            %span &middot;
            = link_to "Edit", edit_user_path(@user)
      %tr
        %td
          %table.uncommon
            %tr
              %th First Name:
              %td= @user.firstName
            %tr
              %th Last Name:
              %td= @user.lastName
            %tr
              %th Username:
              %td= @user.username
            %tr
              %th Email:
              %td= @user.email
        %td
          %table.uncommon
            %tr
              %th Agency:
              %td= @user.agency.present? ? @user.agency.name : "---"
            %tr
              %th Admin:
              %td= @user.admin.present? ? "true" : "false"
            %tr
              %th Roles:
              %td= @user.get_role
            %tr
              %th Enabled:
              %td= @user.enabled

app/views/users/partials/_recipient_index.html.haml
%div.users.container-full.grid-container
  %table.fullTable.col-12.table-shadow.recipient-users-table
    %thead
      %tr
        %th{colspan:"7"}
          .left-filter.lShare
            Filter By:
            %div#filterableOption1.dropdown{:onclick => "pcaFilterableOption1Function()","aria-hidden" => "true"}
              %div#newOpen.droptxt.dropbtn
                Gender
                #pcaFilterableOption1Container.dropdown-content
                  = link_to "All", users_path, class:"backg dropdown-item"
                  = link_to "Female", users_path(gender: 1), class:"backg dropdown-item"
                  = link_to "Male", users_path(gender: 2), class:"backg dropdown-item"
                  = link_to "None Specified", users_path(gender: 0), class:"backg dropdown-item"
              %div#newOpenCaret.dropcaret.dropbtn
                %i.fa.fa-caret-down
                          
          .right-filter.rShare.btnFrame
            = form_tag("/users", method: "get") do
              = text_field_tag(:q, nil, placeholder: "Search")
              = submit_tag("Search")
      %tr
        %th{colspan:"7"}
          %hr
      %tr
        %th.thin
        %th Name
    %tbody
      - if @users.count == 0
        %tr
          %td{colspan: "2"}
            No results found.
      - else
        - @users.each do |user|
          %tr
            %td.thin
              .profile-userpic
                = link_to user_path(user) do
                  = image_tag user.avatar
            %td
              = link_to user.pca.name, user_path(user)

        - if @count > @limit
          - link_count = 0
          - link_total = (@count/@limit.to_f).ceil
          %tr
            %td.page-links{colspan:"7"}
              %div
                - page_count = @page - 2 > 0 && link_total > 5 ? @page - 2 : 1
                - loop do
                  - link_count += 1 
                  - if page_count > 1 && link_count == 1 && link_total > 5
                    = link_to "&#171;".html_safe, request.parameters.merge(page:page_count), class:"page_link"
                  - elsif link_count == 5 && link_total > 5
                    = link_to "&#187;".html_safe, request.parameters.merge(page:page_count), class:"page_link"
                  - else
                    - if page_count == @page
                      = link_to "#{page_count}", request.parameters.merge(page:page_count), class:"page-link current"
                    - else
                      = link_to "#{page_count}", request.parameters.merge(page:page_count), class:"page-link"
                  - break if (page_count * @limit > @count) || link_count > 4
                  - page_count += 1

app/views/users/partials/_recipient_show.html.haml
.recipient-show-container
  .left-column
    = image_tag @user.avatar, class: "avatar"
  .right-column
    %h1= @user.name
    
    %h2 Personal Information
    
    %p
      %strong Gender:
      - if @user.pca.gender == 1
        Female
      - elsif @user.pca.gender == 2
        Male
      - else
        Not Specified
      <br />
      %strong Years of Experience:
      = @user.pca.years_of_experience
      <br />
      %strong= "About #{@user.firstName}:"
      = @user.pca.about_me
    
    %h2 Contact Information
    
    %p 
      - if @user.pca.phoneNumber.present?
        %strong Phone:
        = link_to @user.pca.phoneNumber, "tel:#{@user.pca.phoneNumber}"
        <br />
      - if @user.email.present?
        %strong Email:
        = mail_to @user.email
    
    %h2 Services
    
    %p
      %ul
        - @user.pca.services.each do |service|
          %li= service.serviceName
    
    
    
    = link_to "&larr; Back".html_safe, users_path